services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    ad_component.modificador.subscriber:
        class: AscensoDigital\ComponentBundle\EventListener\RegisterModificadorSubscriber
        arguments: ["@security.token_storage"]
        tags:
            - { name: doctrine.event_subscriber }

    ad_component.datetime_hidden.type:
        class: AscensoDigital\ComponentBundle\Form\Type\DateTimeHiddenType
        tags:
            - { name: form.type, alias: datetime_hidden }

    ad_component.object_hidden.type:
        class: AscensoDigital\ComponentBundle\Form\Type\ObjectHiddenType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: object_hidden }

    ad_component.object_text.type:
        class: AscensoDigital\ComponentBundle\Form\Type\ObjectTextType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: object_text }

    ad_component.object_text_campo.type:
        class: AscensoDigital\ComponentBundle\Form\Type\ObjectTextCampoType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: object_text_campo }

    ad_component.twig_extension:
        class: AscensoDigital\ComponentBundle\Twig\ADExtension
        public: false
        arguments: [ "%ad_component.bootstrap_layout%", "%ad_component.bootstrap_version%" ]
        tags:
            - { name: twig.extension }

    ad_component.help_type_extension:
        class: AscensoDigital\ComponentBundle\Form\Extension\HelpTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    ad_component.addon_type_extension:
        class: AscensoDigital\ComponentBundle\Form\Extension\InputAddonTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    ad_component.date_calendar_type_extension:
            class: AscensoDigital\ComponentBundle\Form\Extension\DateCalendarExtension
            tags:
                - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\DateType }
